---
  data_path_prefix : "pptod/data/multiwoz2.1/data"
  model_name : "t5-base"
  pretrained_path : "pptod/E2E_TOD/ckpt/base/full_training/"
  output_save_path : "E2E_TOD/inference_result/base/full_training/"
  number_of_gpu : 1
  batch_size_per_gpu : 1
