---
  data_path_prefix : "/home/ahmed/RL4E2E/Models/pptod/data/multiwoz/data"
  model_name : "t5-base"
  pretrained_path : "/home/ahmed/RL4E2E/Models/pptod/E2E_TOD/ckpt/base/full_training/"
  output_save_path : "/home/ahmed/RL4E2E/Models/pptod/E2E_TOD/inference_result/base/full_training/"
  number_of_gpu : 1
  batch_size_per_gpu : 1
